name: openblok-linux # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: 'v082' # just for humans, typically '1.2+git' or '1.3.2'
summary:  OpenBlok is a version of the falling block game Tetris
description: |
   OpenBlok is a version of the falling block game Tetris

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots
icon:  openblok_icon.png
title: OpenBlok

apps:
  openblok:
    command: openblok
parts:
  openblok:
    # See 'snapcraft plugins'
    plugin: dump
    source: .
#    build-packages: [default-jre]
#    stage-packages: [default-jre]
    organize:
      openblok: build/
      openblok.1: man/man1/

architectures:
  - build-on: amd64

